# Generated by Django 3.1.7 on 2021-05-08 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webwallet', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ativos',
            new_name='Ativo',
        ),
        migrations.RenameModel(
            old_name='Relatorios',
            new_name='Relatorio',
        ),
    ]
