# Generated by Django 3.1.7 on 2021-05-08 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webwallet', '0002_auto_20210508_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acao',
            name='descricao',
        ),
    ]
