# Generated by Django 3.1.7 on 2021-05-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webwallet', '0003_remove_acao_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acao',
            name='data_cotacao',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='data_compra',
            field=models.DateField(),
        ),
    ]
